services:
  daily-lexika:
    image: nikolai-frontend-daily-lexika:local
    pull_policy: never
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: daily-lexika
        NEXT_PUBLIC_DAILY_LEXIKA_BASE_URL: ${NEXT_PUBLIC_DAILY_LEXIKA_BASE_URL}
        NEXT_PUBLIC_ADMIN_BASE_URL: ${NEXT_PUBLIC_ADMIN_BASE_URL}

  admin:
    image: nikolai-frontend-admin:local
    pull_policy: never
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: admin
        NEXT_PUBLIC_DAILY_LEXIKA_BASE_URL: ${NEXT_PUBLIC_DAILY_LEXIKA_BASE_URL}
        NEXT_PUBLIC_ADMIN_BASE_URL: ${NEXT_PUBLIC_ADMIN_BASE_URL}

  landing-yekaterina:
    image: nikolai-frontend-landing-yekaterina:local
    pull_policy: never
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP_NAME: landing-yekaterina
        NEXT_PUBLIC_DAILY_LEXIKA_BASE_URL: ${NEXT_PUBLIC_DAILY_LEXIKA_BASE_URL}
        NEXT_PUBLIC_ADMIN_BASE_URL: ${NEXT_PUBLIC_ADMIN_BASE_URL}
