services:

  daily-lexika:
    platform: linux/amd64
    container_name: nikolai-frontend-daily-lexika
    image: docker.io/${DOCKERHUB_NAMESPACE}/nikolai-frontend-daily-lexika:${APP_TAG}
    profiles: ["daily-lexika"]
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000

  admin:
    platform: linux/amd64
    container_name: nikolai-frontend-admin
    image: docker.io/${DOCKERHUB_NAMESPACE}/nikolai-frontend-admin:${APP_TAG}
    profiles: ["admin"]
    restart: unless-stopped
    ports:
      - "3080:3080"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3080

  landing-yekaterina:
    platform: linux/amd64
    container_name: nikolai-frontend-landing-yekaterina
    image: docker.io/${DOCKERHUB_NAMESPACE}/nikolai-frontend-landing-yekaterina:${APP_TAG}
    profiles: ["landing-yekaterina"]
    restart: unless-stopped
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=4000
