server:
  port: 8085

spring:
  application:
    name: chinese-flashcards
  datasource:
    url: jdbc:postgresql://localhost:5432/chinese-flashcards
    username: 'postgres'
    password: '1478236950'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'false'
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchanges:
    chinese-flashcards: chinese-flashcards.exchange
  queues:
    delete-chinese-flashcards: chinese-flashcards.delete-chinese-flashcards.queue
  routing-keys:
    delete-chinese-flashcards: chinese-flashcards.delete-chinese-flashcards.routing-key

file-location:
  data-excel: "backend/chinese-flashcards/src/main/resources/static/data/Data.xlsx"