spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vocabulary

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

file-location:
  data-excel: "Data.xlsx"