server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: application-user
          uri: lb://APPLICATION-USER
          predicates:
            - Path=/api/v1/application-users/**
        - id: vocabulary
          uri: lb://VOCABULARY
          predicates:
            - Path=/api/v1/vocabulary/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
