server:
  port: 8080

spring:
  application:
    name: chinese-learning-app
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_chinese_learning_app
    username: 'postgres'
    password: '1478236950'
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show-sql: 'true'
    hibernate:
      ddl-auto: validate
  flyway:
    locations: "classpath:db/migration"
#    enabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

file-location:
  data-excel: "src/main/resources/static/data/Data.xlsx"

#logging:
#  level:
#    root: debug

#file-storage:
#  profile-photo-directory: "backend/file-storage/src/main/resources/static/images/user-%s/profile-photo/"
#  profile-photo-name: "%s-profile-photo%s"
