spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/chinese_learning_app

file-location:
  data-excel: "Data.xlsx"

#file-storage:
#  profile-photo-directory: "static/images/user-%s/profile-photo/"
#  profile-photo-name: "%s-profile-photo%s"
