server:
  port: 8083

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notifications
    username: 'postgres'
    password: '1478236950'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'false'
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchanges:
    notification: notification.exchange
  queues:
    send-welcome-notification: notification.send-welcome-notification.queue
  routing-keys:
    send-welcome-notification: notification.send-welcome-notification.routing-key
