server:
  port: 8081

spring:
  application:
    name: application-user
  datasource:
    url: jdbc:postgresql://postgres:5432/application-user
    username: 'postgres'
    password: '1478236950'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  rabbitmq:
    addresses: rabbitmq:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka